"""initial

Revision ID: 232d68550498
Revises: c8da921f0f5f
Create Date: 2019-05-28 10:09:45.918380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232d68550498'
down_revision = 'c8da921f0f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.Text(_expect_unicode=True), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('image_pic',
    sa.Column('pic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(_expect_unicode=True), nullable=False),
    sa.Column('description', sa.Text(_expect_unicode=True), nullable=False),
    sa.Column('image', sa.Text(_expect_unicode=True), nullable=False),
    sa.Column('image_ext', sa.String(length=15), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_pic')
    op.drop_table('user')
    # ### end Alembic commands ###
